device: cuda
dataset:
  name: ImageNet
  dataset_dir: ~/datasets/ImageNet
  image_size: 224
  n_classes: 1000
model:
  type: imagenet
  name: resnext
  init_mode: pretrain
  features_dim: 128
  resnext:
    initial_channels: 64
    n_blocks: [3, 4, 6, 3]
    cardinality: 32
    base_channels: 4
train:
  resume: False
  seed: 0
  precision: O0
  batch_size: 32
  optimizer: sgd
  base_lr: 0.1
  momentum: 0.9
  nesterov: True
  weight_decay: 1e-4
  output_dir: experiments/imagenet/resnext50_32x4d/exp00
  log_period: 10
  checkpoint_period: 10
  use_tensorboard: True
  distributed: False
  dataloader:
    num_workers: 8
    drop_last: True
    pin_memory: False
validation:
  batch_size: 32
  dataloader:
    num_workers: 8
    drop_last: False
    pin_memory: False
scheduler:
  epochs: 90
  type: CosineAnnealing
  milestones: [30, 60]
  lr_decay: 0.1
tensorboard:
  train_images: False
  val_images: False
  model_params: False
augmentation:
  use_albumentations: True